# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-start_dt']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
    ]
